### ISSUE TITLE
Version Info

### ISSUE THREAD

**Issue by Morketh** [MyEssentials/MyPermissions#9]
I started building a brand new server with your MyTown-2 mod and according to the minecraft forum I've looked through the change log for some kind of reference to the version i need (downloaded the non failing builds) i cant figure out why its crashing. with MyPermissions I'm getting this error in my server read out and then a full stop.

```
[19:41:19] [Server thread/INFO] [FML/]: Itemstack injection complete
[19:41:19] [Server thread/ERROR] [FML/]: Fatal errors were detected during the transition from PREINITIALIZATION to INITIALIZATION. Loading cannot continue
[19:41:19] [Server thread/ERROR] [FML/]: 
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCH mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
    UCH FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1517-1.7.10-universal.jar) 
    UCH Forge{10.13.4.1517} [Minecraft Forge] (forge-1.7.10-10.13.4.1517-1.7.10-universal.jar) 
    UCH MyEssentials-Core{1.7.10-1.13r} [MyEssentials-Core] (MyEssentials-Core-1.7.10-1.13r-universal.jar) 
    UCE MyPermissions{1.7.10-0000r} [MyPermissions] (MyPermissions-1.7.10-34-dev.jar) 
    UCE MyTown2{1.7.10-0.2.0b} [MyTown 2] (MyTown2-1.7.10-0.2.0b.jar) 
    UCH worldedit{6.0-beta-01} [WorldEdit] (worldedit-forge-mc1.7.10-6.0-beta-01.jar) 
[19:41:19] [Server thread/ERROR] [FML/]: The following problems were captured during this phase
[19:41:19] [Server thread/ERROR] [FML/]: Caught exception from MyPermissions
java.lang.NoSuchMethodError: myessentials.Localization.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/Class;)V
    at mypermissions.MyPermissions.preInit(MyPermissions.java:33) ~[MyPermissions.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:?]
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556) [Loader.class:?]
    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88) [FMLServerHandler.class:?]
    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314) [FMLCommonHandler.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117) [lt.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

Versions of each mod are as follows:

```
    mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
    FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1517-1.7.10-universal.jar) 
    Forge{10.13.4.1517} [Minecraft Forge] (forge-1.7.10-10.13.4.1517-1.7.10-universal.jar) 
    MyEssentials-Core{1.7.10-1.13r} [MyEssentials-Core] (MyEssentials-Core-1.7.10-1.13r-universal.jar) 
    MyPermissions{1.7.10-0000r} [MyPermissions] (MyPermissions-1.7.10-34-dev.jar) 
    MyTown2{1.7.10-0.2.0b} [MyTown 2] (MyTown2-1.7.10-0.2.0b.jar) 
    worldedit{6.0-beta-01} [WorldEdit] (worldedit-forge-mc1.7.10-6.0-beta-01.jar)
```

**Comment by dariusc93** [comment]
It looks like its related to MyEssentials and not able to find the Localization class. It does look like things you have may be out of date so you may want to check https://ci.mineguild.net/ for the correct versions.

**Comment by Morketh** [comment]
The MyPermissions came straight off of the Travis build site
digging all around every repository i finally managed to track down the SH1 for MyPermissions in the Build Log got the SHA1 for the MEC Commit used in Build 34 tracked that over to MEC commit ac26095f2a and dug through every build around September 9 (that was the commit date) found the build that actually works with that version of MyPermissions is Build 62 of MEC.
Was coming back to post results when i noticed the message from @dariusc93 seems that i have to use a OLD version of MEC to work with the MyPermissons Build 34 as the one provided on Curseforge.com is newer then the usable version.
Not every one is familiar with the way Github/Travis work it might be easier to specify a version number (in an error report or even on a wiki) with matching builds as i am sure not every one will want to spend 40 minutes digging through Build-logs and Revision history to fix there servers.

First time using the mod. and i think you guys have the right idea here looks like a great work of art keep it up guys.

**Comment by MuresanSergiu** [comment]
`MyEssentials-Core{1.7.10-1.13r} [MyEssentials-Core] (MyEssentials-Core-1.7.10-1.13r-universal.jar) 
    MyPermissions{1.7.10-0000r} [MyPermissions] (MyPermissions-1.7.10-34-dev.jar) 
    MyTown2{1.7.10-0.2.0b} [MyTown 2] (MyTown2-1.7.10-0.2.0b.jar)`

I specify in the changelog on the main forum thread which version of the mods work together. In this case you just needed to downgrade MyPermissions to dev-31

**Comment by Morketh** [comment]
well that was only the beginning of the version changes the Magic version number list is as follows:

```
MyEssentials-Core-1.7.10-60-dev
MyPermissions-1.7.10-31-dev
MyTown2-1.7.10-247-dev
```

also which forum thread are you referring? i looked at minecraftforum.net and the only reference to a change log was 

```
Since there seem to be some issues with CurseForge and we cannot put MyPermissions there, you can download it from here: https://ci.mineguild.net/job/MyPermissions/

Look in the changelog to find out what version you need!
```

i would assume based on those sentences that is reference to the Jenkins build server change log?
.....
.....
.....
Well that seems to be where i over looked things there is a change log on the main minecraftforum.net page its in the spoiler and right at the top in black and white english is all the version numbers needed.

again really great mod guys keep up the good work.
